#!/bin/bash
if [ "$#" = 3 ]; then
   z="$2"
   z=""$z" "$3""
else
  z="$2"
fi

while IFS="," read -r ciudad pais habitantes area
do
   if [ "$z" = "$pais" ]; then
	echo "Ciudades y habitantes de "$z""

	for a in "$pais" ; do
		if [ "$a" = "$z" ] ; then
			echo "Ciudad: $ciudad"
			echo "Número de habitantes: $habitantes"
			echo ""
			habitantes="$habitantes"
		for i in  "$habitantes" ; do
		     x="$((x + i))"
    		done
   		fi
	done
   else
     continue
   fi
done < <(tail -n +2 "$1")
if [ "$x" >=0 ]; then
   echo "El número total de habitantes es $x"
else
   echo ""$z" no es un argumento válido"
fi
